<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-RTFSPNK" ignored="1" name="Expense Create Case" tests="2" failures="1" timestamp="22 May 2019 07:49:15 GMT" time="80.895" errors="0">
  <testcase name="LoginTest" time="24.161" classname="com.fieldez.testcases.TC_CreateCallTest_003"/>
  <testcase name="CreateCallTest" time="35.47" classname="com.fieldez.testcases.TC_CreateCallTest_003">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Call Not Created expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Call Not Created expected [true] but found [false]
at com.fieldez.testcases.TC_CreateCallTest_003.CreateCallTest(TC_CreateCallTest_003.java:215)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- CreateCallTest -->
  <testcase name="UploadCallLevelAttachments" time="0.0" classname="com.fieldez.testcases.TC_CreateCallTest_003">
    <ignored/>
  </testcase> <!-- UploadCallLevelAttachments -->
</testsuite> <!-- Expense Create Case -->
